### ISSUE TITLE
Integration issues

### ISSUE THREAD

**Issue by am1kk** [DavideViolante/pr-reviews-reminder-action#27]
Hi!
I'm struggling with integration for some days and no ideas left what's going wrong.
Always getting `Request failed with status code 401` after `Getting open pull requests...`.
<img width="938" alt="image" src="https://user-images.githubusercontent.com/13099095/120314887-67847c80-c2e4-11eb-9c57-98c7cfb459eb.png">

I have a secret with exactly the same identifier as in code listed below.
<img width="722" alt="image" src="https://user-images.githubusercontent.com/13099095/120315273-d6fa6c00-c2e4-11eb-8e8b-d34a22efad05.png">

Can you please help me?

```
name: PRs reviews reminder
on: [push, pull_request]
jobs:  pr-reviews-reminder:   
 runs-on: ubuntu-latest    
steps:   
- uses: davideviolante/pr-reviews-reminder-action@v1.5.0
- env:        GITHUB_TOKEN: ${{ secrets.ASDF }}      
with:        webhook-url: 'https://hooks.slack.com/services/.../.../...'     
provider: 'slack'
```

**Comment by DavideViolante** [comment]
Try to use 
```
GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

**Comment by am1kk** [comment]
Works for me! Thank you.
