### ISSUE TITLE
How to ignore a PR with specific label?

### ISSUE THREAD

**Issue by anticafe** [DavideViolante/pr-reviews-reminder-action#43]
First of all, thanks for this useful Github Actions.
I wonder if able to ignore some PRs from the reminder if if it has some specific labels (for example "Do not remind", "Do no merge"...), or if its PR title contains the WIP keyword?

**Comment by DavideViolante** [comment]
Hi anticafe, thank you for the feedback. I implemented it in a branch, can you please test it for me?
Edit your yml with
```yml
    - uses: davideviolante/pr-reviews-reminder-action@ignorelabel
```
