### ISSUE TITLE
ignore-label is not working for some PRs

### ISSUE THREAD

**Issue by charles-tbol** [DavideViolante/pr-reviews-reminder-action#73]
Hello, 
I've used `no-reminder` label as `ignore-label` to ignore notifications for old and draft PRs, but the reminder action is still sending those PR links(not all, but some) to Teams channel. As far as I checked `function.js`, it is surely filtering those PRs using `ignore-label` option.
Can you help me resolve that?

**Comment by DavideViolante** [comment]
I need the PR list as JSON to test it out. You can get this list of PR using the [Github API](https://docs.github.com/en/rest/pulls/pulls#list-pull-requests).

**Comment by charles-tbol** [comment]
You can check JSON here and can focus #622 PR as it's one of the wrong ones.
[response.json.zip](https://github.com/DavideViolante/pr-reviews-reminder-action/files/9707344/response.json.zip)

**Comment by DavideViolante** [comment]
I made some tests and it seems working correctly for me.

To make this test i edited `test.js` file replacing `mockPullRequests` var with the JSON you provided to me, then I run these tests:
```js
  it('Should get pull requests with requested reviewers (some reviewers)', () => {
    const pullRequests = getPullRequestsToReview(mockPullRequests);
    assert.strictEqual(pullRequests.length, 5); // there are 5 PRs with requested reviewers
  });

  it('Should get pull requests with requested reviewers and skip those with ignore label', () => {
    const pullRequests = getPullRequestsToReview(mockPullRequests);
    assert.strictEqual(pullRequests.length, 5);
    const pullRequestsWithoutLabel = getPullRequestsWithoutLabel(pullRequests, 'no-reminder');
    assert.strictEqual(pullRequestsWithoutLabel.length, 3); // there are 3 PRs with requested reviewers, 2 has no-reminder label
    console.log(pullRequestsWithoutLabel.map(pr => pr.number)); // [ 736, 731, 668 ]
  });
```

Are you correctly using v2.1.1 in the yml inside the github action? Can you paste here the yml of the Github action please?

**Comment by charles-tbol** [comment]
I'm using v2.1.1.

name: 'PR Reviewer Auto Assign'
on:
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize]

jobs:
  add-reviews:
    runs-on: ubuntu-latest
    if: ${{ !github.event.pull_request.draft }}
    steps:
      - uses: kentaro-m/auto-assign-action@v1.2.3
      - uses: davideviolante/pr-reviews-reminder-action@v2.1.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          webhook-url: '***'
          provider: 'msteams'
          channel: ''
          github-provider-map: 'jackson-miller-tbol:jackson.miller@thebankoflondon.com,robert-ditmore-tbol:robert.ditmore@thebankoflondon.com,charles-tbol:charles.park@@thebankoflondon.com,miguel-tbol:miguel.murillo@thebankoflondon.com,munirahzahari:munirah.zahari@thebankoflondon.com,mandrew-f:andrew.moore@thebankoflondon.com,hwarcup-tbol:hill.warcup@thebankoflondon.com,zackwatts:zack.watts@thebankoflondon.com,ahmed-mansour-tbol:ahmed.mansour@thebankoflondon.com'
          ignore-label: 'no-reminder'

**Comment by charles-tbol** [comment]
Thank you, @DavideViolante. It worked for me.
