### ISSUE TITLE
User name on Teams is something weird.

### ISSUE THREAD

**Issue by charles-tbol** [DavideViolante/pr-reviews-reminder-action#77]
Hello, Davide
Hope you're doing fine.

Can you check following screenshots? For some cases, we have incorrect user names on Teams.

![BD128C7E-5925-44B6-8FE2-ADC27F731DA3](https://user-images.githubusercontent.com/102837909/200584608-3fddee25-0e84-404d-ae70-bb5f426f9b15.png)

`abraham-oh-tbol UPN` should be `abraham-oh-tbol`.

![26E8FDA3-71D8-4D06-96DC-948DE24A8EE5](https://user-images.githubusercontent.com/102837909/200584852-96c8c736-3bb7-4947-bddf-a2729f7a4e93.png)

`mandrew-f UPN` should actually be `charles-tbol`.

**Comment by DavideViolante** [comment]
Can you please try to use
```
- uses: davideviolante/pr-reviews-reminder-action@master
- ```

**Comment by charles-tbol** [comment]
> Can you please try to use
> 
> ```yaml
> - uses: davideviolante/pr-reviews-reminder-action@master
> ```

Thank you for the fix. I'll try `master` branch then. Will that also fix wrong matching like `mandrew-f UPN->charles-tbol`?

**Comment by DavideViolante** [comment]
Let me know if this works, the Teams implementation was made by a contributor. I removed UPN from the [code](https://github.com/DavideViolante/pr-reviews-reminder-action/commit/4acaabea8d1525c840e0abeae78a5cbc321ea37d) on master branch, but not released a new version until you confirm me that this works correctly.

**Comment by charles-tbol** [comment]
Hello, Davide. 
We're getting `Error: axios is not a function` once we update action to use `master` branch.

**Comment by charles-tbol** [comment]
It seems working now. Thank you.
