### ISSUE TITLE
PR reviewers vs reminder notifications

### ISSUE THREAD

**Issue by charles-tbol** [DavideViolante/pr-reviews-reminder-action#78]
![C007AB65-2E27-4BEB-81BC-213E12B0D631](https://user-images.githubusercontent.com/102837909/203564859-f2e13394-fb05-486c-8d45-045fe8cc2775.png)

PR reviewers are Zack and Charles, but reminder notifications are going to Abraham and Andrew.

**Comment by DavideViolante** [comment]
Can you please provide me the JSON of the PR list as returned from the GitHub APIs? Thank you, I'll try to look at it asap

**Comment by charles-tbol** [comment]
How can I get that PR list as JSON?

**Comment by DavideViolante** [comment]
With [GitHub API](https://docs.github.com/en/rest/pulls/pulls#list-pull-requests), you did the same also in [this issue](https://github.com/DavideViolante/pr-reviews-reminder-action/issues/73#issuecomment-1267021726)

**Comment by DavideViolante** [comment]
Thank you very much for the JSON. It seems like that the PR https://github.com/DavideViolante/pr-reviews-reminder-action/pull/68 was bugged and also the tests implemented were not strong enough.

I'm currently implementing a fix. Can you please try 
```yml
- uses: davideviolante/pr-reviews-reminder-action@fixteams
```

Thank you for your testing.

**Comment by charles-tbol** [comment]
Hello, Davide. 
Is this bug fully fixed now then?

**Comment by DavideViolante** [comment]
Hi @charles-tbol , do you have any news? Thanks

**Comment by charles-tbol** [comment]
Hello, Davide
I don't think I see the issues again. I'll let you know if anything wrong comes out.

**Comment by DavideViolante** [comment]
Thank you for testing it out in a real scenario, it helps me a lot. Feel free to comment here if this issue happens again, or open a new issue if something else happens.
