### ISSUE TITLE
ignore-label accepts only one label

### ISSUE THREAD

**Issue by KhushalGupta** [DavideViolante/pr-reviews-reminder-action#90]
I am ignoring PR's that are created from github_actions and draft.
![Screen Shot 2023-01-31 at 09 44 22](https://user-images.githubusercontent.com/17666396/215711381-65b71b0a-a9ff-45fd-9d59-e2fb47c7ece3.png)

But the action still does not ignore it.
<img width="593" alt="Screen Shot 2023-01-31 at 09 45 24" src="https://user-images.githubusercontent.com/17666396/215711610-32280494-7320-48a3-9ed7-e94df3ab9378.png">

That's how I use it.
`ignore-label: 'dependencies, github_actions, draft'`

**Comment by DavideViolante** [comment]
Ignore label accept 1 label only.

**Comment by KhushalGupta** [comment]
> Ignore label accept 1 label only.

Can we enhance it to accept more ?

**Comment by DavideViolante** [comment]
Can you try v2.4.0 and let me know? Thanks

**Comment by DavideViolante** [comment]
Can you try v2.5.0 and let me know? Thanks
